### ISSUE TITLE
能不能在 pydig.py 中增加个排序的选项开关？

### ISSUE THREAD

**Issue by jzp820927** [xyuanmu/checkiptools#11]
能不能在 pydig.py 中增加个排序的选项开关，把生成的 dig_range.txt 文件排下序，不然我剔除官方字段，眼睛都找花了。

**Comment by xyuanmu** [comment]
抱歉回复晚了，pydig.py里有一个设置：dig_sort_range = 1，整合IP段到 googleip.txt 里是排好序的，而且会自动剔除 ip_range_bad.txt 里有的IP段，只要把官方IP段放到 ip_range_bad.txt 里就行了。

**Comment by jzp820927** [comment]
额，我都忘记什么时候发的这个 issues 了，既然实现了，我就 close 了。
